CREATE TABLE warehouse (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(160) NOT NULL
);
CREATE TABLE location (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
 parent_id BIGINT REFERENCES location(id),
 code VARCHAR(40) NOT NULL,
 name VARCHAR(160) NOT NULL,
 type VARCHAR(20) NOT NULL CHECK(type IN ('ZONE','AISLE','RACK','SHELF','STAGING')),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(warehouse_id, code)
);
CREATE TABLE product (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 sku VARCHAR(60) NOT NULL UNIQUE,
 name VARCHAR(160) NOT NULL,
 description VARCHAR(2000) NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE SEQUENCE pallet_code_seq;
CREATE TABLE pallet (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(40) NOT NULL UNIQUE,
 product_id BIGINT NOT NULL REFERENCES product(id),
 location_id BIGINT REFERENCES location(id),
 quantity INTEGER NOT NULL CHECK(quantity >= 0),
 status VARCHAR(20) NOT NULL CHECK(status IN ('ACTIVE','DISPATCHED')),
 version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL,
 CHECK((status = 'ACTIVE' AND quantity > 0 AND location_id IS NOT NULL)
    OR (status = 'DISPATCHED' AND quantity = 0 AND location_id IS NULL))
);
CREATE TABLE stock_movement (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 pallet_id BIGINT NOT NULL REFERENCES pallet(id),
 type VARCHAR(20) NOT NULL CHECK(type IN ('RECEIPT','TRANSFER','DISPATCH')),
 quantity INTEGER NOT NULL CHECK(quantity > 0),
 balance_after INTEGER NOT NULL CHECK(balance_after >= 0),
 source_id BIGINT REFERENCES location(id),
 destination_id BIGINT REFERENCES location(id),
 actor VARCHAR(100) NOT NULL,
 reference VARCHAR(300) NOT NULL DEFAULT '',
 request_id UUID NOT NULL UNIQUE,
 created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX pallet_location_idx ON pallet(location_id);
CREATE INDEX pallet_product_idx ON pallet(product_id);
CREATE INDEX movement_pallet_idx ON stock_movement(pallet_id, created_at);
CREATE INDEX movement_created_idx ON stock_movement(created_at DESC);
