CREATE SEQUENCE receiving_session_code_seq;
CREATE TABLE receiving_session (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(40) NOT NULL UNIQUE,
 warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
 receiving_location_id BIGINT NOT NULL REFERENCES location(id),
 delivery_note VARCHAR(100) NOT NULL DEFAULT '',
 supplier VARCHAR(160) NOT NULL DEFAULT '',
 expected_pallet_count INTEGER CHECK (expected_pallet_count > 0),
 note VARCHAR(1000) NOT NULL DEFAULT '',
 status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN','COMPLETED')),
 opened_by VARCHAR(100) NOT NULL,
 opened_at TIMESTAMPTZ NOT NULL,
 completed_at TIMESTAMPTZ,
 version BIGINT NOT NULL DEFAULT 0
);
ALTER TABLE pallet ADD COLUMN receiving_session_id BIGINT REFERENCES receiving_session(id);
ALTER TABLE pallet ADD COLUMN first_put_away_at TIMESTAMPTZ;
CREATE INDEX pallet_receiving_session_idx ON pallet(receiving_session_id);
